### ISSUE TITLE
Mapsui.Samples.Forms.Android throws resource exception at startup

### ISSUE THREAD

**Issue by janusw** [Mapsui/Mapsui#1134]
When building and running Mapsui.Samples.Forms.Android, I recently see this exception on startup:

```
Android.Content.Res.Resources+NotFoundException: Resource ID #0x7f0b0081
  at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <9d4325e9cba34e898f60fae8e84f1f4f>:0
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0002a] in <9d4325e9cba34e898f60fae8e84f1f4f>:0
  at Android.Views.LayoutInflater.Inflate (System.Int32 resource, Android.Views.ViewGroup root) [0x0003a] in /Users/builder/azdo/_work/278/s/xamarin-android/src/Mono.Android/obj/Release/monoandroid10/android-29/mcw/Android.Views.LayoutInflater.cs:660
  at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.OnCreate (Android.OS.Bundle savedInstanceState, Xamarin.Forms.Platform.Android.ActivationFlags flags) [0x0007f] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\FormsAppCompatActivity.cs:248
  at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\FormsAppCompatActivity.cs:211
  at Mapsui.Samples.Forms.Droid.MainActivity.OnCreate (Android.OS.Bundle bundle) [0x00053] in /Users/janus/github/Mapsui/Samples/Mapsui.Samples.Forms/Mapsui.Samples.Forms.Android/MainActivity.cs:33
  at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x00010] in /Users/builder/azdo/_work/278/s/xamarin-android/src/Mono.Android/obj/Release/monoandroid10/android-29/mcw/Android.App.Activity.cs:2691
  at at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.5(intptr,intptr,intptr)
  at android.content.res.Resources$NotFoundException: Resource ID #0x7f0b0081
  at at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:237)
  at at android.content.res.Resources.loadXmlResourceParser(Resources.java:2400)
  at at android.content.res.Resources.getLayout(Resources.java:1252)
  at at android.view.LayoutInflater.inflate(LayoutInflater.java:530)
  at at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
  at at crc64ebe4dbe10159bf74.MainActivity.n_onCreate(Native Method)
  at at crc64ebe4dbe10159bf74.MainActivity.onCreate(MainActivity.java:38)
  at at android.app.Activity.performCreate(Activity.java:8037)
  at at android.app.Activity.performCreate(Activity.java:8021)
  at at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
  at at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3478)
  at at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3657)
  at at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
  at at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
  at at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
  at at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2121)
  at at android.os.Handler.dispatchMessage(Handler.java:106)
  at at android.os.Looper.loop(Looper.java:248)
  at at android.app.ActivityThread.main(ActivityThread.java:7787)
  at at java.lang.reflect.Method.invoke(Native Method)
  at at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
  at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
```

This happens on MacOS with Visual Studio for Mac 8.9.10 and Xamarin.Android 11.1.0.17. Not sure since when it happens and what triggered it.

**Comment by janusw** [comment]
Does anyone else see this? When building on Mac or on Windows?

**Comment by janusw** [comment]
The error is gone with Xamarin.Android 11.2.2.1.

**Comment by janusw** [comment]
I cannot even reproduce it with Xamarin.Android 11.1.0.17 now. Closing.
