### ISSUE TITLE
InflateException when running Mapsui.Samples.Droid

### ISSUE THREAD

**Issue by janusw** [Mapsui/Mapsui#1497]
When running Mapsui.Samples.Droid from current master on a Samsung Galaxy S21 (Android 12), I get the following:

```
Android.Views.InflateException: Binary XML file line #1 in Mapsui.Samples.Droid.Mapsui.Samples.Droid:layout/activity_main: Binary XML file line #1 in Mapsui.Samples.Droid.Mapsui.Samples.Droid:layout/content_main: Error inflating class Mapsui.UI.Android.MapControl ---> Android.Views.InflateException: Binary XML file line #1 in Mapsui.Samples.Droid.Mapsui.Samples.Droid:layout/content_main: Error inflating class Mapsui.UI.Android.MapControl ---> Java.Lang.ClassNotFoundException: Mapsui.UI.Android.MapControl ---> Java.Lang.ClassNotFoundException: Didn't find class "Mapsui.UI.Android.MapControl" on path: DexPathList[[zip file "/data/app/~~coal7vO9DM2jiJjxQuIHrQ==/Mapsui.Samples.Droid.Mapsui.Samples.Droid-Az3B_GfJg5Yud1hh1j34QQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~coal7vO9DM2jiJjxQuIHrQ==/Mapsui.Samples.Droid.Mapsui.Samples.Droid-Az3B_GfJg5Yud1hh1j34QQ==/lib/arm64, /data/app/~~coal7vO9DM2jiJjxQuIHrQ==/Mapsui.Samples.Droid.Mapsui.Samples.Droid-Az3B_GfJg5Yud1hh1j34QQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
  at java.lang.ClassNotFoundException: Didn't find class "Mapsui.UI.Android.MapControl" on path: DexPathList[[zip file "/data/app/~~coal7vO9DM2jiJjxQuIHrQ==/Mapsui.Samples.Droid.Mapsui.Samples.Droid-Az3B_GfJg5Yud1hh1j34QQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~coal7vO9DM2jiJjxQuIHrQ==/Mapsui.Samples.Droid.Mapsui.Samples.Droid-Az3B_GfJg5Yud1hh1j34QQ==/lib/arm64, /data/app/~~coal7vO9DM2jiJjxQuIHrQ==/Mapsui.Samples.Droid.Mapsui.Samples.Droid-Az3B_GfJg5Yud1hh1j34QQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
  at at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
  at at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
  at at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
  at at java.lang.Class.classForName(Native Method)
  at at java.lang.Class.forName(Class.java:454)
  at at android.view.LayoutInflater.createView(LayoutInflater.java:819)
  at at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
  at at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
  at at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
  at at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
  at at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
  at at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
  at at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1267)
  at at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
  at at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
  at at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
  at at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
  at at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
  at at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
  at at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
  at at crc6488e8941134e9c189.MainActivity.n_onCreate(Native Method)
  at at crc6488e8941134e9c189.MainActivity.onCreate(MainActivity.java:31)
  at at android.app.Activity.performCreate(Activity.java:8282)
  at at android.app.Activity.performCreate(Activity.java:8262)
  at at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
  at at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3996)
  at at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4188)
  at at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
  at at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
  at at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
  at at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2425)
  at at android.os.Handler.dispatchMessage(Handler.java:106)
  at at android.os.Looper.loopOnce(Looper.java:226)
  at at android.os.Looper.loop(Looper.java:313)
  at at android.app.ActivityThread.main(ActivityThread.java:8582)
  at at java.lang.reflect.Method.invoke(Native Method)
  at at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:563)
  at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
  --- End of inner exception stack trace ---
  at java.lang.ClassNotFoundException: Mapsui.UI.Android.MapControl
  at at java.lang.Class.classForName(Native Method)
  at at java.lang.Class.forName(Class.java:454)
  at at android.view.LayoutInflater.createView(LayoutInflater.java:819)
  at at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
  at at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
  at at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
  at at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
  at at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
  at at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
  at at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1267)
  at at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
  at at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
  at at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
  at at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
  at at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
  at at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
  at at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
  at at crc6488e8941134e9c189.MainActivity.n_onCreate(Native Method)
  at at crc6488e8941134e9c189.MainActivity.onCreate(MainActivity.java:31)
  at at android.app.Activity.performCreate(Activity.java:8282)
  at at android.app.Activity.performCreate(Activity.java:8262)
  at at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
  at at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3996)
  at at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4188)
  at at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
  at at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
  at at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
  at at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2425)
  at at android.os.Handler.dispatchMessage(Handler.java:106)
  at at android.os.Looper.loopOnce(Looper.java:226)
  at at android.os.Looper.loop(Looper.java:313)
  at at android.app.ActivityThread.main(ActivityThread.java:8582)
  at at java.lang.reflect.Method.invoke(Native Method)
  at at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:563)
  at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
  at Caused by: java.lang.ClassNotFoundException: Didn't find class "Mapsui.UI.Android.MapControl" on path: DexPathList[[zip file "/data/app/~~coal7vO9DM2jiJjxQuIHrQ==/Mapsui.Samples.Droid.Mapsui.Samples.Droid-Az3B_GfJg5Yud1hh1j34QQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~coal7vO9DM2jiJjxQuIHrQ==/Mapsui.Samples.Droid.Mapsui.Samples.Droid-Az3B_GfJg5Yud1hh1j34QQ==/lib/arm64, /data/app/~~coal7vO9DM2jiJjxQuIHrQ==/Mapsui.Samples.Droid.Mapsui.Samples.Droid-Az3B_GfJg5Yud1hh1j34QQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
  at at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
  at at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
  at at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
  at ... 35 more
  --- End of inner exception stack trace ---
  at android.view.InflateException: Binary XML file line #1 in Mapsui.Samples.Droid.Mapsui.Samples.Droid:layout/content_main: Error inflating class Mapsui.UI.Android.MapControl
  at Caused by: java.lang.ClassNotFoundException: Mapsui.UI.Android.MapControl
  at at java.lang.Class.classForName(Native Method)
  at at java.lang.Class.forName(Class.java:454)
  at at android.view.LayoutInflater.createView(LayoutInflater.java:819)
  at at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
  at at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
  at at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
  at at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
  at at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
  at at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
  at at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1267)
  at at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
  at at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
  at at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
  at at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
  at at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
  at at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
  at at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
  at at crc6488e8941134e9c189.MainActivity.n_onCreate(Native Method)
  at at crc6488e8941134e9c189.MainActivity.onCreate(MainActivity.java:31)
  at at android.app.Activity.performCreate(Activity.java:8282)
  at at android.app.Activity.performCreate(Activity.java:8262)
  at at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
  at at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3996)
  at at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4188)
  at at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
  at at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
  at at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
  at at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2425)
  at at android.os.Handler.dispatchMessage(Handler.java:106)
  at at android.os.Looper.loopOnce(Looper.java:226)
  at at android.os.Looper.loop(Looper.java:313)
  at at android.app.ActivityThread.main(ActivityThread.java:8582)
  at at java.lang.reflect.Method.invoke(Native Method)
  at at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:563)
  at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
  at Caused by: java.lang.ClassNotFoundException: Didn't find class "Mapsui.UI.Android.MapControl" on path: DexPathList[[zip file "/data/app/~~coal7vO9DM2jiJjxQuIHrQ==/Mapsui.Samples.Droid.Mapsui.Samples.Droid-Az3B_GfJg5Yud1hh1j34QQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~coal7vO9DM2jiJjxQuIHrQ==/Mapsui.Samples.Droid.Mapsui.Samples.Droid-Az3B_GfJg5Yud1hh1j34QQ==/lib/arm64, /data/app/~~coal7vO9DM2jiJjxQuIHrQ==/Mapsui.Samples.Droid.Mapsui.Samples.Droid-Az3B_GfJg5Yud1hh1j34QQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
  at at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
  at at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
  at at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
  at ... 35 more
  --- End of inner exception stack trace ---
  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0008e] in <00c315a988634383b446eff646084784>:0
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00063] in <00c315a988634383b446eff646084784>:0
  at Android.App.Activity.SetContentView (System.Int32 layoutResID) [0x00018] in /Users/builder/azdo/_work/1/s/xamarin-android/src/Mono.Android/obj/Release/monoandroid10/android-29/mcw/Android.App.Activity.cs:5737
  at Mapsui.Samples.Droid.MainActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x00009] in /Users/janus/github/Mapsui/Samples/Mapsui.Samples.Droid/MainActivity.cs:32
  at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x00010] in /Users/builder/azdo/_work/1/s/xamarin-android/src/Mono.Android/obj/Release/monoandroid10/android-29/mcw/Android.App.Activity.cs:2704
  at at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.1(intptr,intptr,intptr)
  at android.view.InflateException: Binary XML file line #1 in Mapsui.Samples.Droid.Mapsui.Samples.Droid:layout/activity_main: Binary XML file line #1 in Mapsui.Samples.Droid.Mapsui.Samples.Droid:layout/content_main: Error inflating class Mapsui.UI.Android.MapControl
  at Caused by: android.view.InflateException: Binary XML file line #1 in Mapsui.Samples.Droid.Mapsui.Samples.Droid:layout/content_main: Error inflating class Mapsui.UI.Android.MapControl
  at Caused by: java.lang.ClassNotFoundException: Mapsui.UI.Android.MapControl
  at at java.lang.Class.classForName(Native Method)
  at at java.lang.Class.forName(Class.java:454)
  at at android.view.LayoutInflater.createView(LayoutInflater.java:819)
  at at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
  at at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
  at at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
  at at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
  at at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
  at at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
  at at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1267)
  at at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
  at at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
  at at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
  at at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
  at at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
  at at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
  at at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
  at at crc6488e8941134e9c189.MainActivity.n_onCreate(Native Method)
  at at crc6488e8941134e9c189.MainActivity.onCreate(MainActivity.java:31)
  at at android.app.Activity.performCreate(Activity.java:8282)
  at at android.app.Activity.performCreate(Activity.java:8262)
  at at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
  at at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3996)
  at at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4188)
  at at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
  at at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
  at at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
  at at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2425)
  at at android.os.Handler.dispatchMessage(Handler.java:106)
  at at android.os.Looper.loopOnce(Looper.java:226)
  at at android.os.Looper.loop(Looper.java:313)
  at at android.app.ActivityThread.main(ActivityThread.java:8582)
  at at java.lang.reflect.Method.invoke(Native Method)
  at at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:563)
  at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
  at Caused by: java.lang.ClassNotFoundException: Didn't find class "Mapsui.UI.Android.MapControl" on path: DexPathList[[zip file "/data/app/~~coal7vO9DM2jiJjxQuIHrQ==/Mapsui.Samples.Droid.Mapsui.Samples.Droid-Az3B_GfJg5Yud1hh1j34QQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~coal7vO9DM2jiJjxQuIHrQ==/Mapsui.Samples.Droid.Mapsui.Samples.Droid-Az3B_GfJg5Yud1hh1j34QQ==/lib/arm64, /data/app/~~coal7vO9DM2jiJjxQuIHrQ==/Mapsui.Samples.Droid.Mapsui.Samples.Droid-Az3B_GfJg5Yud1hh1j34QQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
  at at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
  at at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
  at at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
  at ... 35 more

```

**Comment by janusw** [comment]
I cannot reproduce this any more. After cleaning up and rebuilding, the error is gone. Sorry for the noise.
