### ISSUE TITLE
Offline map and zoom/unzoom causes app crash

### ISSUE THREAD

**Issue by dinonovak** [Mapsui/Mapsui#1510]
HI,
I am getting unhadled error when clicking on zoom/unzoom after I switch to offline map.
an way to disable this option on map or handle thisevent/ error as it is now causing app to crash.

See error below:

[AndroidRuntime] FATAL EXCEPTION: main
[AndroidRuntime] Process: com.mobiexplore.caminoimota, PID: 22962
[AndroidRuntime] android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
[AndroidRuntime]   at Mapsui.UI.Forms.MapView.HandlerTap (System.Object sender, Mapsui.UI.TappedEventArgs e) [0x00051] in <8e64338d61e3456bbee149587d8ab173>:0 
[AndroidRuntime]   at Mapsui.UI.Forms.MapControl.OnSingleTapped (Mapsui.Geometries.Point screenPosition) [0x00012] in <8e64338d61e3456bbee149587d8ab173>:0 
[AndroidRuntime]   at Mapsui.UI.Forms.MapControl.OnTouch (System.Object sender, SkiaSharp.Views.Forms.SKTouchEventArgs e) [0x002e5] in <8e64338d61e3456bbee149587d8ab173>:0 
[AndroidRuntime]   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in <1f756ecb97534575954067defc16b036>:0 
[AndroidRuntime]   at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <46f2b43332da4d80916267d3aa03d5ff>:0 
[AndroidRuntime]   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <46f2b43332da4d80916267d3aa03d5ff>:0 
[AndroidRuntime]   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <46f2b43332da4d80916267d3aa03d5ff>:0 
[AndroidRuntime]   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.63(intptr,intptr)
[AndroidRuntime] 	at mono.java.lang.RunnableImplementor.n_run(Native Method)
[AndroidRuntime] 	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
[AndroidRuntime] 	at android.os.Handler.handleCallback(Handler.java:914)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:100)
[AndroidRuntime] 	at android.os.Looper.loop(Looper.java:225)
[AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:7563)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)
[MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] Android.Runtime.JavaProxyThrowable: Exception of type 'Android.Runtime.JavaProxyThrowable' was thrown.
[MonoDroid]   --- End of managed Android.Runtime.JavaProxyThrowable stack trace ---
[MonoDroid] android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
[MonoDroid]   at Mapsui.UI.Forms.MapView.HandlerTap (System.Object sender, Mapsui.UI.TappedEventArgs e) [0x00051] in <8e64338d61e3456bbee149587d8ab173>:0 
[MonoDroid]   at Mapsui.UI.Forms.MapControl.OnSingleTapped (Mapsui.Geometries.Point screenPosition) [0x00012] in <8e64338d61e3456bbee149587d8ab173>:0 
[MonoDroid]   at Mapsui.UI.Forms.MapControl.OnTouch (System.Object sender, SkiaSharp.Views.Forms.SKTouchEventArgs e) [0x002e5] in <8e64338d61e3456bbee149587d8ab173>:0 
[MonoDroid]   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in <1f756ecb97534575954067defc16b036>:0 
[MonoDroid]   at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <46f2b43332da4d80916267d3aa03d5ff>:0 
[MonoDroid] 	at android.os.Handler.handleCallback02-18 17:48:25.324 I/MonoDroid(22962):   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <46f2b43332da4d80916267d3aa03d5ff>:0 
[MonoDroid]   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <46f2b43332da4d80916267d3aa03d5ff>:0 
[MonoDroid]   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.63(intptr,intptr)
[MonoDroid] 	at mono.java.lang.RunnableImplementor.n_run(Native Method)
[MonoDroid] 	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
[MonoDroid] 	at android.os.Handler.handleCallback(Handler.java:914)
[MonoDroid] 	at android.os.Handler.dispatchMessage(Handler.java:100)
[MonoDroid] 	at android.os.Looper.loop(Looper.java:225)
[MonoDroid] 	at java.lang.reflect.Method.invoke(Native Method)
[MonoDroid] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
[MonoDroid] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)
[MonoDroid] 
[Process] Sending signal. PID: 22962 SIG: 9

**Comment by charlenni** [comment]
Do you think it is possible to get some more information? Which version of Mapsui? Which zoom buttons do you use? Such things would be helpful.

**Comment by dinonovak** [comment]
Xamarin.Forms with mapsui 3.0.2

I am clicking on standard butons that are overlayed on map (+ and - icons)

![pic](https://user-images.githubusercontent.com/18152490/154743464-2957c407-2045-4f50-9a75-4221a87e3772.png)

**Comment by janusw** [comment]
> HI, I am getting unhadled error when clicking on zoom/unzoom after I switch to offline map.

What does "after I switch to offline map" mean here? Can you explain what kind of offline map you are using?

**Comment by mohcine21** [comment]
Hi , 
 please i want to add offline mode to mapsui but i didnt know about it , can some one help me :

  var tileLayer = OpenStreetMap.CreateTileLayer();
                HttpTileSource tileSource = tileLayer.TileSource as HttpTileSource;
                map.Layers.Add(tileLayer);
                map.Widgets.Add(new Mapsui.Widgets.ScaleBar.ScaleBarWidget(map) { TextAlignment = Mapsui.Widgets.Alignment.Center, HorizontalAlignment = Mapsui.Widgets.HorizontalAlignment.Left, VerticalAlignment = Mapsui.Widgets.VerticalAlignment.Bottom });
                mapView.Map = map;
                mapView.PinClicked += Map_PinClicked;

**Comment by mohcine21** [comment]
var routerDb = new RouterDb();
          var jsonFileName = @"morocco-car.osm.routerdb";
          var assembly = typeof(TourneeView).GetTypeInfo().Assembly;
            Stream stream = assembly.GetManifestResourceStream($"Test_project.{jsonFileName}");
            var profile = Vehicle.Car.Fastest(); 
...
