### ISSUE TITLE
[System.InvalidOperationException] MapControl.MapControlMouseMove

### ISSUE THREAD

**Issue by EjiHuang** [Mapsui/Mapsui#1775]
Hi Mapsui development team.

**Describe the bug**
The background of my program updates features all the time. Regarding the addition and deletion of features, I have used lock for synchronization. However, when I drag the map, there is a probability that this exception will appear. The problem seems to be in the foreach of the Mapsui.Extensions.FeatureExtensions.GetExtent method. Currently, this problem is only triggered when dragging the map.

Mapsui version: 4.0.0-beta.5

```c#
public static MRect? GetExtent(this IEnumerable<IFeature> features)
{
    MRect? result = null;
    foreach (var feature in features)
    {
        if (feature.Extent is null) continue;
        result = result is null ? new MRect(feature.Extent): result.Join(feature.Extent);
    }
    return result;
}
```

**Additional context**
The exception output:
```c#
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
at System.ThrowHelper.ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
at System.Collections.Generic.List`1.Enumerator.MoveNext()
at Mapsui.Extensions.FeatureExtensions.GetExtent(IEnumerable`1 features)
at Mapsui.Map.get_Extent()
at Mapsui.LimitedViewport.Transform(MPoint position, MPoint previousPosition, Double deltaResolution, Double deltaRotation)
at Mapsui.UI.Wpf.MapControl.MapControlMouseMove(Object sender, MouseEventArgs e)
at System.Windows.Input.MouseEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
at System.Windows.Input.InputManager.ProcessStagingArea()
at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
at System.Windows.Threading.Dispatcher.Run()
at System.Windows.Application.RunDispatcher(Object ignore)
at System.Windows.Application.RunInternal(Window window)
at System.Windows.Application.Run()
at Test.UI.App.Main()
```

**Comment by pauldendulk** [comment]
Thanks for the clear bug report. What kind of layer is involved? Could you show how it is created?

**Comment by pauldendulk** [comment]
Perhaps you use a MemoryLayer and assign it with a feature collection created in your code. 

The default of the ```IEnumerable<IFeature>``` is a ConcurrentBag which is thread save. If you create your MemoryLayer with a thread save collection that would fix the problem in this situation.

MemoryLayer.Features implementation:
```csharp
public IEnumerable<IFeature> Features { get; set; } = new ConcurrentBag<IFeature>();
```

**Comment by pauldendulk** [comment]
Just noticed that the ConcurrentBag was not yet used in beta.5. It is part of the just released beta.6 https://github.com/Mapsui/Mapsui/pull/1655.

**Comment by EjiHuang** [comment]
Hi @pauldendulk . Thanks for your answer. I am using ```GenericCollectionLayer<IEnumerable<IFeature>>``` as Layer. Now, I'm updating to beta.6 and trying to use ```ConcurrentBag<IFeature>```.

**Comment by EjiHuang** [comment]
I found ```ConcurrentBag<IFeature>``` difficult to perform Remove operation. I had to give it up. When I switched back to IEnumerable<IFeature> and continued testing, I found the law of this issue. This exception will only be triggered in Visual Studio debug mode. Running the compiled program directly will not cause this exception.

**Comment by pauldendulk** [comment]
You can use another thread save collection type instead. Perhaps the https://learn.microsoft.com/en-us/dotnet/standard/collections/thread-safe/

You can either use that type to create the instance of the GenericCollectionLayer or you could assign the MemoryLayer.Features field with it.

The fact that it does not show in release mode is probably coincidence. This issue only occurs with a certain timing, perhaps it does not show in release mode (yet) because release mode is faster.

**Comment by EjiHuang** [comment]
Thank you very much. It should be a problem with my code at the moment. I'll try your suggestion to fix it.

**Comment by EjiHuang** [comment]
Hi @pauldendulk. After I switched to ```GenericCollectionLayer<ConcurrentBag<IFeature>>```, the exception didn't happen anymore. Everything works fine. However, when I used ```Animation```, I found out that the ```Layer.Animations``` is a ```List<IFeature>```. The exception is triggered when I remove an item.

```c#
// Add
_animationFunc = () => Animation.UpdateAnimations(_boxSelectionStyle, animations);
lock (_syncObject)
{
    _mapService.AnimationsLayer.Animations.Add(_animationFunc);
}

// Remove
lock (_syncObject)
{
    _mapService.AnimationsLayer.Animations.Remove(_animationFunc);
}
```

**Comment by pauldendulk** [comment]
In the case of the animation you could use a thread save class in your IProvider implementation.

We are working on a permanent solution for this.
