### ISSUE TITLE
Exception on RunOnUIThread

### ISSUE THREAD

**Issue by pauldendulk** [Mapsui/Mapsui#1846]
**Describe the bug**
OutOfMemoryException Exception on RunOnUIThread, while logged memory usage was low and stable (25 MB).

**To Reproduce**
1. Run the application for several days and write exceptions to the log 😁

**Expected behavior**
No exception

**Platform:**
 - MAUI on Windows desktop

**Stacktrace**
```console
[2023-02-17 00:54:18] A crash occurred:System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Runtime.InteropServices.ComWrappers.<TryGetOrCreateComInterfaceForObjectInternal>g____PInvoke|7_0(ObjectHandleOnStack comWrappersImpl, Int64 wrapperId, ObjectHandleOnStack instance, CreateComInterfaceFlags flags, IntPtr* retValue)
   at System.Runtime.InteropServices.ComWrappers.TryGetOrCreateComInterfaceForObjectInternal(ComWrappers impl, Object instance, CreateComInterfaceFlags flags, IntPtr& retValue)
   at System.Runtime.InteropServices.ComWrappers.GetOrCreateComInterfaceForObject(Object instance, CreateComInterfaceFlags flags)
   at WinRT.ComWrappersSupport.CreateCCWForObjectForABI(Object obj, Guid iid)
   at ABI.Microsoft.UI.Dispatching.IDispatcherQueueMethods.TryEnqueue(IObjectReference _obj, DispatcherQueueHandler callback)
   at Mapsui.UI.Maui.MapControl.RunOnUIThread(Action action)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

**Remarks**
- It is not certain that this is a Mapsui problem. 
- We can add a catch in RunOnUIThread.
- We call SKGLView.InvalidateSurface in RunOnUIThread. 
- Not clear to me from the stack trace if the problem is with the method that is called (I don't see it in the stack trace) or in the dispatch method itself.

**Comment by FrozDark** [comment]
SKXamlCanvas already does invalidation on UI thread through dispatcher so it is not necessary to MapsUI to do it

**Comment by pauldendulk** [comment]
Closing this issue because it could not be reproduced so far and I don't see a specific way to proceed on this. One improvement that has already been made is that the map exception are not synchronized on the main thread.

A more general solution is to rewrite some of our code to use less invalide calls.
