### ISSUE TITLE
Crash - Mapsui.UI.Maui.MapControl.InvalidateTimerCallback  System.NullReferenceException

### ISSUE THREAD

**Issue by polygonsheep** [Mapsui/Mapsui#2105]
**Mapsui Version**
Mapsui.Maui 4.0.0

**Mapsui Platform**
Maui.  Not tested on other platforms.

**Device**
iOS Simulator, iPhone, iPad.  Most prominent on Simulator

**Describe the bug**
System.NullReferenceException: Object reference not set to an instance of an object.
  at at Mapsui.UI.Maui.MapControl.InvalidateTimerCallback(Object state)
  at at System.Threading.TimerQueueTimer.<>c.<.cctor>b__27_0(Object state)
  at at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
  at at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
  at at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
  at at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
  at at System.Threading.TimerQueue.FireNextTimers()
  at at System.Threading.TimerQueue.System.Threading.IThreadPoolWorkItem.Execute()
  at at System.Threading.ThreadPoolWorkQueue.DispatchItemWithAutoreleasePool(Object workItem, Thread currentThread)
  at at System.Threading.ThreadPoolWorkQueue.Dispatch()
  at at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
  at at System.Threading.Thread.StartCallback()

**To Reproduce**
I have an app with multiple Content Pages. One of those pages loads Mapsui and displays the map. Switching between a non-map Content page and the content page with the map it will eventually crash when loading/displaying the map page. Usually crashes within 5 - 10 page switches. Page switching about 1 or 2 seconds apart will make it crash faster, but it's crashed when not switching fast as well.

**Expected behavior**
I would expect it to handle null exceptions and not crash

**Screenshots**
N/A

**Additional context**
Doesn't happen every time, but if you continue to switch between a map page and non-map page it will crash usually within 5 - 10 switches.  Tried with both Singleton Pages and Transient Pages for the map page, same results. Here's my Map Page code.

XML
        <mapsui:MapView Grid.Row="1"
                        x:Name="MapsuiMap"/>

PageViewModel Constructor (passes in MapsuiMaps as MapView mapView)

            mapView.Map?.Layers.Add(Mapsui.Tiling.OpenStreetMap.CreateTileLayer());
            mapView.Map.Navigator.RotationLock = true;
            mapView.Map.Navigator.OverrideZoomBounds = new Mapsui.MMinMax(mapView.Map.Navigator.Resolutions[19], mapView.Map.Navigator.Resolutions[15]);
            mapView.MyLocationEnabled = true;
            Position p = new Position(32.00454, -81.09149);
            mapView.Map.Home = n => n.CenterOnAndZoomTo(p.ToMapsui(), n.Resolutions[17]);

PageViewModel OnAppearing

            mapView.Map.Navigator.CenterOn(myNewPosition.ToMapsui());
            mapView.Pins.Clear();

            mapView.Pins.Add(new Pin(new MapView())
            {
                Position = new Position(myNewPosition),
                Type = PinType.Pin,
                Label = "Blah",
                Address = "Blah",
                //Color = new Microsoft.Maui.Graphics.Color(25 / 255f, 25 / 255f, 200 / 255f),
                Scale = 0.7f,
            });

I'll try to make a simple app to show the problem and upload later if needed.

**Comment by inforithmics** [comment]
Thanks for the Bug report will be fixed in this pull request.
https://github.com/Mapsui/Mapsui/pull/2108

**Comment by pauldendulk** [comment]
The MR is merged. Please test again on the next release.
