### ISSUE TITLE
Pinch zoom causes map to pan even with PanLock on

### ISSUE THREAD

**Issue by mikernet** [Mapsui/Mapsui#2696]
**Mapsui Version**
4.1.7, 5.0.0-beta.1

**Mapsui Platform**
Uno

**Device**
Android

**Describe the bug**
Zooming in and out via the widget keeps the current center of the map in the same spot, but the pinch zoom gesture does not - it pans up vertically on zoom out and pans down on zoom in, even with `PanLock` set to `true`.

This is problematic since I don't want the user to be able to move from whatever is in the center of the map but I do want them to be able to zoom.

**To Reproduce**
```cs
TrackingMap.Map.Layers.Add(OpenStreetMap.CreateTileLayer());
TrackingMap.Map.Navigator.RotationLock = true;
TrackingMap.Map.Navigator.PanLock = true;

TrackingMap.Map.Widgets.Add(new ZoomInOutWidget {
    HorizontalAlignment = Mapsui.Widgets.HorizontalAlignment.Right,
    VerticalAlignment = Mapsui.Widgets.VerticalAlignment.Top,
});
``` 

**Expected behavior**
The center of the map should stay where it is when pinch zooming.

**Comment by pauldendulk** [comment]
Thanks for the report. I reproduced this in todays main (v5). It is certainly not intended to work like this. I remember getting this problem fixed for mouse wheel zoom. It should also be fixed for pinch zoom. At least in v5.

**Comment by pauldendulk** [comment]
The bug is fixed with this PR and will be part of 5.0.0-beta.2. https://github.com/Mapsui/Mapsui/pull/2699

I personally won't prioritize fixing this bug in v4.

**Comment by mikernet** [comment]
I seem to be having a lot of other issues with v5, so not sure how realistic it will be for me to be able to update to that soon, but that is what it is I guess.

**Comment by pauldendulk** [comment]
@mikernet Please report the bugs.

**Comment by mikernet** [comment]
This still seems to be happening on 5.0.0-beta.17. I can't try beta.18 because it won't seem to work on uno android native nor skia renderers. It's not as extreme as it was before, but it does still pan.

**Comment by pauldendulk** [comment]
I have been looking into Lock and came up with another PR: https://github.com/Mapsui/Mapsui/pull/3097

I can not reproduce your problem in todays main. 

However, the problem you are pointing at might be fixed in this PR: https://github.com/Mapsui/Mapsui/pull/3089 which will be fixed in beta.21, which should be released this week.

**Comment by mikernet** [comment]
Tried to test but getting this in Android+SkiaRenderer with `beta.21`:

```
{System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotSupportedException: SKSwapChainPanel is not supported for Skia based platforms
   at SkiaSharp.Views.Windows.SKSwapChainPanel..ctor() in /_/source/SkiaSharp.Views.Uno/SkiaSharp.Views.Uno.WinUI.Skia/SKSwapChainPanel.Skia.cs:line 22
   at Mapsui.UI.WinUI.SKSwapChainPanelRenderControl..ctor(MapControl owner, Action`1 renderCallback)
   at Mapsui.UI.WinUI.RenderControl.CreateControl(MapControl owner, Action`1 renderCallback)
   at Mapsui.UI.WinUI.MapControl..ctor()
   at Volt.Views.JobSites.AddJobSitePage.InitializeComponent() in C:\Projects\Clients\3E\3E-Volt\Source\Volt.Client\obj\Debug\net9.0-android\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator\AddJobSitePage_608b1e1fdb28c72aaae460dcef74419f.cs:line 57
   at Volt.Views.JobSites.AddJobSitePage..ctor() in C:\Projects\Clients\3E\3E-Volt\Source\Volt.Client\Views\JobSites\AddJobSitePage.xaml.cs:line 15

[omitted rest of irrelevant stack trace]
```

That should have been fix now no?

**Comment by mikernet** [comment]
I tried without SkiaRenderer and got:

```
{System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Java.Lang.ClassNotFoundException: crc6462b5399ce6dea9db.MapControl
 ---> Java.Lang.ClassNotFoundException: Didn't find class "crc6462b5399ce6dea9db.MapControl" on path: DexPathList[[zip file "/data/app/~~dV0RA1EOtRJ5ktOwM58EFA==/ca.x3epower.volt-RQe2rJyvOior8U6Dedqr1Q==/base.apk"],nativeLibraryDirectories=[/data/app/~~dV0RA1EOtRJ5ktOwM58EFA==/ca.x3epower.volt-RQe2rJyvOior8U6Dedqr1Q==/lib/arm64, /data/app/~~dV0RA1EOtRJ5ktOwM58EFA==/ca.x3epower.volt-RQe2rJyvOior8U6Dedqr1Q==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
```
