### ISSUE TITLE
Problem with ScaleBarWidget

### ISSUE THREAD

**Issue by 88madri** [Mapsui/Mapsui#367]
Sometimes this error occurs

An unhandled exception of type 'System.ArgumentException' occurred in WindowsBase.dll
'NaN' is not a valid value for property 'X1'.

I have a this portion of code.
 
```
Map = new Map()
{
     ZoomMode = ZoomMode.KeepWithinResolutionsAndAlwaysFillViewport,
     PanMode = PanMode.KeepViewportWithinExtents
};

Loaded += MapControlLoaded;
```

```
private void MapControlLoaded(object sender, RoutedEventArgs e)
{
            TryInitializeViewport();
            UpdateSize();
            InitZoomAnimation();
            Focusable = true;
            LoadScaleWidget();
}

        private void LoadScaleWidget()
        {
            Map.Widgets.Add(new Mapsui.Widgets.ScaleBar.ScaleBarWidget(Map)
            {
                MaxWidth = 160,
                Font = new Mapsui.Styles.Font { FontFamily = "sans serif", Size = 16 },
                ScaleBarMode = Mapsui.Widgets.ScaleBar.ScaleBarMode.Single,
                TextAlignment = Mapsui.Widgets.Alignment.Center,
                HorizontalAlignment = Mapsui.Widgets.HorizontalAlignment.Center,
                VerticalAlignment = Mapsui.Widgets.VerticalAlignment.Bottom
            });
        }
```

**Comment by charlenni** [comment]
Thank you for your message.

It would be helpfull, if you could say, which renderer (Wpf or Skia) do you use and if there is a calling stack for this error. What did you before and where was your map center? Is it at startup or while moving the map?

**Comment by 88madri** [comment]
Hi. It's with WPF renderer. I would try to give you a call stack tomorrow. 
First I try to load the scalebar after new Map() but always this error did happen, then I thought it was resolved by using the Loaded Event of the map but now sometimes this occurs.

Usually I have a saved Zoom and Map Center Position so at the beginning I try to load this saved values. Then sometimes this error appears even when the Main Window is not displayed.

**Comment by 88madri** [comment]
Here is the call stack

Unhandled Exception: System.ArgumentException: 'NaN' is not a valid value for property 'X1'.
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at Mapsui.Rendering.Xaml.ScaleBarWidgetRenderer.Draw(Canvas canvas, ScaleBarWidget scaleBar)
   at Mapsui.Rendering.Xaml.WidgetRenderer.Render(Object target, IEnumerable`1 widgets)
   at Mapsui.Rendering.Xaml.MapRenderer.Render(Object target, IViewport viewport, IEnumerable`1 layers, IEnumerable`1 widgets, Color background)
   at SVT.WPF.Mapping.MapControl.RenderWpf()
   at SVT.WPF.Mapping.MapControl.CompositionTargetRendering(Object sender, EventArgs e)
   at System.Windows.WeakEventManager.ListenerList.DeliverEvent(Listener& listener, Object sender, EventArgs args, Type managerType)
   at System.Windows.WeakEventManager.ListenerList.DeliverEvent(Object sender, EventArgs args, Type managerType)
   at System.Windows.WeakEventManager.DeliverEvent(Object sender, EventArgs args)
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

**Comment by 88madri** [comment]
Maybe the viewport is initialized after the load event??

**Comment by charlenni** [comment]
When do you create your map layer? Add ScaleBarWidget after this.

**Comment by 88madri** [comment]
Ok. Everything works right now. 
Is it possible to modify the size of scalebar based on the Size of the MapControl?

**Comment by charlenni** [comment]
Change ScaleBarWidget.MaxWidth for this. It's the maximum width of scale bar in pixels.

**Comment by pauldendulk** [comment]
Perhaps there could be some check on null values to prevent a crash.

**Comment by charlenni** [comment]
I try to look into this in the next days.

**Comment by pauldendulk** [comment]
This is now fixed in the scalebar projection check.
