### ISSUE TITLE
Issue while adding scalebar to map

### ISSUE THREAD

**Issue by Mohakalilam** [Mapsui/Mapsui#617]
Here is my code. I am creating an UWP form application and while adding scalebar I get the issue. I have checked CRS and Transformation and they are not null.

mapView.Map.Layers.Add(OpenStreetMap.CreateTileLayer());
            mapView.Map.Widgets.Add(new ScaleBarWidget(mapView.Map) { ScaleBarMode = ScaleBarMode.Both, MarginX = 10, MarginY = 10 });
            mapView.Map.Widgets.Add(new Mapsui.Widgets.Zoom.ZoomInOutWidget(mapView.Map) { MarginX = 20, MarginY = 40 });

**Error: Value cannot be null, parameter Buffer in SkiaSharp.MeatureText**
Stack:

   at SkiaSharp.SKPaint.MeasureText(IntPtr buffer, IntPtr length, SKRect& bounds)
   at SkiaSharp.SKPaint.MeasureText(Byte[] text, SKRect& bounds)
   at SkiaSharp.SKPaint.MeasureText(String text, SKRect& bounds)
   at Mapsui.Rendering.Skia.ScaleBarWidgetRenderer.Draw(SKCanvas canvas, Double screenWidth, Double screenHeight, ScaleBarWidget scaleBar, Single layerOpacity)
   at Mapsui.Rendering.Skia.WidgetRenderer.Render(Object target, Double screenWidth, Double screenHeight, IEnumerable`1 widgets, Single layerOpacity)
   at Mapsui.Rendering.Skia.MapRenderer.Render(SKCanvas canvas, IViewport viewport, IEnumerable`1 layers, IEnumerable`1 widgets, Color background)
   at Mapsui.Rendering.Skia.MapRenderer.Render(Object target, IViewport viewport, IEnumerable`1 layers, IEnumerable`1 widgets, Color background)
   at Mapsui.UI.Uwp.MapControl._renderTarget_PaintSurface(Object sender, SKPaintSurfaceEventArgs e)
   at SkiaSharp.Views.UWP.SKXamlCanvas.OnPaintSurface(SKPaintSurfaceEventArgs e)
   at SkiaSharp.Views.UWP.SKXamlCanvas.DoInvalidate()
   at SkiaSharp.Views.UWP.SKXamlCanvas.Invalidate()
   at SkiaSharp.Views.UWP.SKXamlCanvas.OnSizeChanged(Object sender, SizeChangedEventArgs e)

**Comment by pauldendulk** [comment]
Thanks for reporting. I will take a look.

**Comment by Mohakalilam** [comment]
This is to inform that after using the latest beta version this issue is gone. This issue came up in stable versions.

**Comment by pauldendulk** [comment]
ah, so the problem was in 1.4.8?

**Comment by Mohakalilam** [comment]
yes paul.

**Comment by pauldendulk** [comment]
Thanks for the feedback. In that case I will postpone this and will probably not fix it at all. It is better to put my limited time into 2.0.

**Comment by pauldendulk** [comment]
I got this error when upgrading to Mapsui 1.68. Perhaps you did the same. The fix should be to stay on 1.60.
